### ISSUE TITLE
AttributeError when reading a .log file

### ISSUE THREAD

**Issue by JSoto26** [pchtsp/orloge#1]
I'm getting the following error when trying to read a .log file generated by GUROBI:

![imagen](https://user-images.githubusercontent.com/64360610/80307665-c830b400-87ca-11ea-9d9e-eecdc6c83730.png)

This error shows up for some files, like 'detalles_sol_2', but for other files, like 'detalles_sol_1', everything seems to work just fine...

[detalles_sol_2.log](https://github.com/pchtsp/orloge/files/4535311/detalles_sol_2.log)
[detalles_sol_1.log](https://github.com/pchtsp/orloge/files/4535310/detalles_sol_1.log)

I believe I'm doing everything correctly when using the library:

![imagen](https://user-images.githubusercontent.com/64360610/80307707-15148a80-87cb-11ea-8dd5-41caaa426336.png)

**Comment by pchtsp** [comment]
Thanks for the example and the data. Check with the new version in the master and see if it works, I've added your file as a new test in the code, too.

```
pip install -U git+https://github.com/pchtsp/orloge
```

**Comment by JSoto26** [comment]
I ran the new version using over 30 different .log files and not a single error! Thank you very much!

**Comment by pchtsp** [comment]
cool! I'll close the issue then. Feel free to open a new one if you anything weird again.
