### ISSUE TITLE
elapsed time in cplex progress missing for version 20.1

### ISSUE THREAD

**Issue by gromicho** [pchtsp/orloge#2]
The latest version of cplex changed slightly the format of the log: the times at the end are justified to the right and hence preceded by a variable number of white spaces. 

The log attached ends with:
Total (root+branch&cut) =  300.03 sec. (91622.74 ticks)

Method CPLEX.get_time(self) parses this line with:

regex = "Total \(root\+branch&cut\) = {0} sec\. \({0} ticks\)".format(self.numberSearch)

That fails, but if changed to:

regex = "Total \(root\+branch&cut\) =\s+{0} sec\. \({0} ticks\)".format(self.numberSearch)

then all works as expected. 

[trivial.True.True.cplex.300.log](https://github.com/pchtsp/orloge/files/6423270/trivial.True.True.cplex.300.log)

**Comment by pchtsp** [comment]
Thanks, I think the new version (in github, for now) should include the change. I've added your log to the test dataset. 
If you want to install this version you can do:

```
python -m pip install https://github.com/pchtsp/orloge/archive/master.zip
```

I'm curious about this log: is it missing a whole part of solution stats at the end? Or is that how the new logs are shown with CPLEX 20.1.0.0?
I'm talking about cuts statistics, solution status, solver status, bound, gap, etc. This is an example from another log:

```
Clique cuts applied:  1
Implied bound cuts applied:  3
Flow cuts applied:  0
Mixed integer rounding cuts applied:  2
Zero-half cuts applied:  3
Lift and project cuts applied:  2
Gomory fractional cuts applied:  6

Root node processing (before b&c):
  Real time             =    2.17 sec. (1492.28 ticks)
Parallel b&c, 12 threads:
  Real time             =    0.00 sec. (0.00 ticks)
  Sync time (average)   =    0.00 sec.
  Wait time (average)   =    0.00 sec.
                          ------------
Total (root+branch&cut) =    2.17 sec. (1492.28 ticks)

Solution pool: 1 solution saved.

MIP - Integer optimal, tolerance (0/40):  Objective =  1.8041792998e+04
Current MIP best bound =  1.8003715497e+04 (gap = 38.0775, 0.21%)
Solution time =    2.17 sec.  Iterations = 5199  Nodes = 0 (1)
Deterministic time = 1492.30 ticks  (686.16 ticks/sec)
```

**Comment by gromicho** [comment]
Thanks!

I did not edit the log at all, that is how CPLEX made it.

Cheers Joaquim
