### ISSUE TITLE
ol.get_info_log_solver() function not working

### ISSUE THREAD

**Issue by ebongo1** [pchtsp/orloge#3]
I tried this: `ol.get_info_log_solver('C:/Users/ebongo/AppData/Local/Programs/Python/Python38/Lib/site-packages/pulp/solverdir/cbc/win/64', 'PULP_CBC_CMD')`

But I keep receiving this error: "AttributeError: module 'orloge' has no attribute 'get_info_log_solver'"
Am I referencing this function incorrectly? The log that this outputs would be extremely useful for my project so any help with this would be greatly appreciated.

**Comment by pchtsp** [comment]
Check the Readme for examples https://github.com/pchtsp/orloge

**Comment by ebongo1** [comment]
I have. Is there any other support I can get for this? I have followed exactly what the examples say to do and still cannot find/get the output dictionary.

**Comment by pchtsp** [comment]
Could you provide the complete code you're executing as well as the log
file you're trying to parse?

Also, could you download the test logfiles (e.g., this one:
https://github.com/pchtsp/orloge/blob/master/tests/data/cbc298-app1-2.out)
and see if it works for those files?

This tool does not get the log from the solver as your example appears to
assume This package reads a log file that has already been exported from
CBC and is stored in a file.

**Comment by ebongo1** [comment]
I did try using “CBC” as well and that still didn’t work. Am I supposed to see an outputted json file or something? Or will the json just be printed to the same log file?

Erin Bongo
Associate Operations Research Analyst
The MITRE Corporation
413-494-0094
MITRE<https://www.mitre.org/> | Solving Problems for a Safer World™

From: Franco Peschiera ***@***.***>
Sent: Monday, May 10, 2021 2:51 PM
To: pchtsp/orloge ***@***.***>
Cc: Erin M Bongo ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [pchtsp/orloge] ol.get_info_log_solver() function not working (#3)

The solver name argument is wrong. It's "CBC". As I said, check the
examples.

**Comment by pchtsp** [comment]
Hello!
I think I now know why: the documentation is wrong (outdated). You should use the `ol.get_info_solver` function instead of the `ol.get_info_log_solver`. Everything else remains the same. Sorry about that. On the other hand, if you'd provided a complete reproducible example, that would had helped me find the error sooner.
Hope you can still profit from the library.

I've now updated the README.

**Comment by ebongo1** [comment]
Thank you! Now it is working for CBC! And I understand, however it is a bit difficult to send complete examples of my code since parts of it are not able to be shared to others outside of my organization. But I appreciate you helping me through this anyway!
