### ISSUE TITLE
Parser for GUROBI is not getting the latest log info

### ISSUE THREAD

**Issue by ebongo1** [pchtsp/orloge#4]
I am now testing out this plugin with GUROBI as my solver, and it seems that it is not parsing the latest log information. See attached log file for reference (reformatted as a .txt file). The parsed output should have the gap = 0.3040% however it is still printing the gap as 69.1818% from the first output in the log. I also attached a screenshot of the command prompt output for reference. I also am pasting some relevant code for this example as well:

```
def configure_solver():
    if GUROBI().available():
        solver = GUROBI(logPath='C:/Users/ebongo/Documents/ABRA/ace/testLog.out')

    elif CPLEX_CMD().available():
        solver = CPLEX_CMD(msg=1, logPath='C:/Users/ebongo/Documents/ABRA/ace/testLog.out')
        
    elif PULP_CBC_CMD().available():
        solver = PULP_CBC_CMD(msg=1, logPath='C:/Users/ebongo/Documents/ABRA/ace/testLog.out')

    else:
        logger.warning("No solver found")

    solver.optionsDict["gapRel"] = params.MIP_gap
    solver.msg = 1  # display output to console

    # set the solver time limit
    if params.use_time_limit:
        solver.timeLimit = params.time_limit

    return solver
```

```

    model.writeLP('ABRA.lp')
    solver = configure_solver()
    model.solve(solver)

    solver_output_dict = ol.get_info_solver('C:/Users/ebongo/Documents/ABRA/ace/testLog.out', 'GUROBI')
    best_bound = solver_output_dict["best_bound"]
    best_solution = solver_output_dict["best_solution"]
    rel_gap = solver_output_dict["gap"]
    print(solver_output_dict)
    logger.info("Best bound: %s" % best_bound)
    logger.info("Best solution: %s" % best_solution)
    logger.info("Relative gap: %s" % rel_gap)
```

![gurobiLog](https://user-images.githubusercontent.com/83773112/118304939-539fe480-b4b5-11eb-887c-e60883dac822.PNG)
[testLog.txt](https://github.com/pchtsp/orloge/files/6480200/testLog.txt)

**Comment by pchtsp** [comment]
Your example file includes three different runs of gurobi (so three log
files in one). It appears the library is taken the first one. But maybe you
should delete the file before solving each time, that way there will always
be only one run.

**Comment by ebongo1** [comment]
Ok I will try that out. Thank you!

-Erin

From: Franco Peschiera ***@***.***>
Sent: Saturday, May 15, 2021 10:00 AM
To: pchtsp/orloge ***@***.***>
Cc: Erin M Bongo ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [pchtsp/orloge] Parser for GUROBI is not getting the latest log info (#4)

Your example file includes three different runs of gurobi (so three log
files in one). It appears the library is taken the first one. But maybe you
should delete the file before solving each time, that way there will always
be only one run.
