### ISSUE TITLE
gap_rel ZeroDivisionError

### ISSUE THREAD

**Issue by ebongo1** [pchtsp/orloge#5]
My team has run into an issue with this package when our objective value is zero. It seems like in your code you have a calculation that doesn't allow the objective value to be zero because it causes a "ZeroDivisionError". Why is that? See attached picture for context. 
![image](https://user-images.githubusercontent.com/83773112/123266491-140fe380-d4ca-11eb-9567-74c557cf0570.png)

**Comment by pchtsp** [comment]
good question. Could you provide the log file so I can add it to the unit tests?

**Comment by ebongo1** [comment]
Attached is the solver log file 
[solver.txt](https://github.com/pchtsp/orloge/files/6717248/solver.txt)
